[package]
name = "dao_randomness"
version = "1.0.0"
authors = []

[addresses]
QubitCo="5ca7cb14573af2a12cbadfabaa49437d4243ebbf97c4e0ac03b5d9cae484a02a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
