[package]
name = "dao_randomness"
version = "1.0.0"
authors = []

[addresses]
QubitCo="1ba787561854dd4443968bdd38b0dc2cdb852c0f65be7702d69a92e367535091"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
