[package]
name = "dao_randomness"
version = "1.0.0"
authors = []

[addresses]
QubitCo="3ce2dbc7eaba2f8012189d3ba63dfd46c00c28c4eb3732771b3bcf5a37e71ef3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
