[package]
name = "dao_randomness"
version = "1.0.0"
authors = []

[addresses]
QubitCo="852c844262fa204073c3d7ecc19fb352d23ed0a3022ba2b34efff60c82ec3d88"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
