[package]
name = "dao_randomness"
version = "1.0.0"
authors = []

[addresses]
QubitCo="ceb1952b202180a3c222a037d45a89e39db8c4227a7e47b5da30f1169bb2791d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
